### PR TITLE
Fix: Explicitly point to certifi certificate chain.

### PR DESCRIPTION
**Pull request by htgoebel**

### CODE REVIEW

**Comment by edsu** [comment]
I apologize it's taken so long to respond about this. Was this change actually needed?

**Comment by htgoebel** [comment]
> Was this change actually needed?

Yes, of course. Otherwise I would not have taken my time implementing it and creating a pull-request.

**Comment by edsu** [comment]
Do you have an example RSS URL I can try to replicate the problem?

**Comment by htgoebel** [comment]
Not after 3 years :-\

**Comment by edsu** [comment]
I'm sorry it took so long for me to ask. I'm closing now since I've not had this problem.

**Comment by htgoebel** [comment]
This is very disappointing. "Works for me" rarely is a good solution for an existing pull-request.

**Comment by edsu** [comment]
If you aren't able to supply an example that helps me reproduce the problem I'm kind of stuck. The really disappointing thing that happened here is that it took me three years to respond, and I'm very sorry about that.

**Pull request closed without merging**
